version: "3.8"

x-commons: &commons
  image: mongo:7.0.5
  command: mongod --replSet rs0

services:
  go_mongodb_sample_db:
    container_name: go_mongodb_sample_db
    <<: *commons
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  go_mongodb_sample_db_ci:
    container_name: go_mongodb_sample_db_ci
    <<: *commons
    ports:
      - "27018:27017"

  go_mongodb_sample_echo:
    container_name: go_mongodb_sample_echo
    build: .
    ports:
      - "1323:1323"
    volumes:
      - .:/app
      - .env:/app/.env
    working_dir: /app
    command: sh -c 'go mod tidy && air'
    depends_on:
      - go_mongodb_sample_db

volumes:
  mongodb_data:
